Listabierta\Bundle\MunicipalesBundle\Entity\Candidate:
    type: entity
    table: candidate
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\CandidateRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        lastname:
            type: string
            length: 255
        dni:
            type: string
            length: '20'
        email:
            type: string
            length: 255
        phone:
            type: string
            length: '20'
 
        admin_id:
            type: integer
            nullable: TRUE
                       
        academic_level:
            type: integer
            nullable: TRUE
            
        languages:
            type: array
            nullable: TRUE
            
        job_experience:
            type: array
            nullable: TRUE
            
        town_activities:
            type: array
            nullable: TRUE
            
        govern_priorities:
            type: array
            nullable: TRUE        
        
        public_values:
            type: array
            nullable: TRUE 
            
        motivation_text:
            type: text
            nullable: TRUE
            
        town_activities_explanation:
            type: array
            nullable: TRUE
            
        additional_info:
            type: text
            nullable: TRUE
            
        url_info:
            type: text
            nullable: TRUE
            
        status:
            type: integer
            nullable: TRUE
                            
    lifecycleCallbacks: {  }
