Listabierta\Bundle\MunicipalesBundle\Entity\Province:
    type: entity
    table: provinces_spain
    repositoryClass: Listabierta\Bundle\MunicipalesBundle\Entity\ProvinceRepository
    id:
        id:
            type: smallint
            id: true
            generator:
                strategy: AUTO
    fields:
        community_id:
            type: smallint
            
        name:
            type: string
            length: '45'
    lifecycleCallbacks: {  }
